language: generic
sudo: required
servics:
  - docker

before_install:
  - docker build -t juchilian/rarejob-tutor-checker -f Dockerfile.dev .

script:
  - ./scripts/py-test.sh
  # - docker run -e CI=true juchilian/rarejob-tutor-checker ./scripts/py-test.sh
