FROM python:alpine

WORKDIR /usr/src/app

RUN apk add --no-cache bash
# install dependencies
RUN pip install --upgrade pip
RUN python3 -m pip install pipenv
COPY Pipfile .
COPY Pipfile.lock .
RUN pipenv install --system --deploy --ignore-pipfile
RUN pipenv sync

COPY . /usr/src/app