version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: "selenium-hub"
    ports:
      - 4444:4444
  selenium:
    image: selenium/node-chrome-debug
    container_name: "chrome"
    shm_size: 2g
    depends_on:
      - selenium-hub
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python3 server/index.py
    depends_on:
      - selenium
    volumes:
      - .:/usr/src/app/
    environment:
      SELENIUM_URL: http://selenium-hub:4444/wd/hub
