version: "3"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    shm_size: 2g
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - chrome
    volumes:
      - .:/usr/src/app/
    environment:
      SELENIUM_URL: http://chrome:4444/wd/hub
    tty: true

networks:
  web:
    driver: bridge
